#!/usr/bin/env bash

set -ex

export NODE_VERSION=14.16.0

# Install Node
if [ -z $(asdf plugin list | grep nodejs) ]; then
    asdf plugin add nodejs
fi
if [ -z $(asdf list nodejs | grep $NODE_VERSION) ]; then
    asdf install nodejs $NODE_VERSION
fi
asdf local nodejs $NODE_VERSION
asdf reshim nodejs $NODE_VERSION
