//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homepage.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int ID { get; set; }
        public System.DateTime VisitTime { get; set; }
        public string url { get; set; }
        public string VisitorIsp { get; set; }
        public string VisitorCity { get; set; }
        public string VisitorRegion { get; set; }
        public string VisitorCountry { get; set; }
        public string VisitorPostalCode { get; set; }
        public Nullable<double> VisitorLat { get; set; }
        public Nullable<double> VisitorLon { get; set; }
        public string VisitorTimeZone { get; set; }
        public string VisitorIpAddress { get; set; }
        public string VisitorRawIp { get; set; }
        public string VisitorName { get; set; }
    }
}
